### ISSUE TITLE
Serilog .NET 8 Windows Service (worker) using BackgroundService Log file not found

### ISSUE THREAD

**Issue by tekbyts** [serilog/serilog-extensions-logging#239] opened 2024-01-24 18:30 UTC
My goal is to use Serilog for file logging in a Windows service using the .NET 8 Worker template.

While in the debug mode, I can see console logs. I just couldn't find the log file.
While running as a windows service, I don't see the log file being created so i can't find the logs. And not sure where the console logs will appear when running as a service. 

Here is my config and code. Am I missing something?

`appsettings.json`

```
{
  "Serilog": {
    "MinimumLevel": {
      "Default": "Information",
      "Override": {
        "Microsoft": "Information",
        "System": "Information"
      }
    },
    "Using": ["Serilog.Sinks.Console", "Serilog.Sinks.File"],
    "WriteTo": [
      { "Name": "Console" },
      {
        "Name": "File",
        "Args": {
          "path": "log.txt",
          "rollingInterval": "Day"
        }
      }
    ]
  }
}
```
`Program.cs`

```
using GettingStartedSvc;
using Serilog;

var builder = Host.CreateApplicationBuilder(args);

// The initial bootstrap logger is able to log errors during start-up.
// It's fully replaced by the logger configured in `UseSerilog()`.
Log.Logger = new LoggerConfiguration().WriteTo.Console().CreateBootstrapLogger();

Log.Information("Starting up...");

try
{
    builder.Logging.AddSerilog();
    // configures the app to work as a Windows Service.
    builder.Services.AddWindowsService(ops =>
    {
        ops.ServiceName = "DotNet Joke Service";
    });
    builder.Services.AddSingleton<JokeService>();
    builder.Services.AddHostedService<WindowsBackgroundService>();

    var host = builder.Build();
    host.Run();
}
catch (Exception ex)
{
    Log.Fatal(ex, "An unhandled exception occured during bootstrapping");
}
finally
{
    Log.CloseAndFlush();
}
```
```
`JokeService.cs`

namespace GettingStartedSvc;

public sealed class JokeService
{
    public string GetJoke()
    {
        Joke joke = _jokes.ElementAt(Random.Shared.Next(_jokes.Count));
        return $"{joke.Setup}{Environment.NewLine}{joke.Punchline}";
    }

    private readonly HashSet<Joke> _jokes = new()
    {
        new Joke("What's the best thing about a Boolean?", "Even if you're wrong, you're only off by a bit."),
        new Joke("What's the object-oriented way to become wealthy?", "Inheritance"),
        new Joke("Why did the programmer quit their job?", "Because they didn't get arrays.")
    };

}

readonly record struct Joke(string Setup, string Punchline);
```

`WindowsBackgroundService.cs`

```
namespace GettingStartedSvc;

public sealed class WindowsBackgroundService : BackgroundService
{
    private readonly ILogger<WindowsBackgroundService> _logger;
    private readonly JokeService _jokeService;

    public WindowsBackgroundService(
        ILogger<WindowsBackgroundService> logger,
        JokeService jokeService
    )
    {
        _logger = logger;
        _jokeService = jokeService;
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        try
        {
            while (!stoppingToken.IsCancellationRequested)
            {
                string joke = _jokeService.GetJoke();
                _logger.LogWarning("{Joke}", joke);

                await Task.Delay(TimeSpan.FromMinutes(1), stoppingToken);
            }
        }
        catch (OperationCanceledException opCanceledEx)
        {

        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "{Message}", ex.Message);
            Environment.Exit(1);
        }
        while (!stoppingToken.IsCancellationRequested)
        {
            var joke = _jokeService.GetJoke();
            _logger.LogWarning("{Joke}", joke);
            await Task.Delay(TimeSpan.FromMinutes(1), stoppingToken);
        }
    }
}
```

**Comment by Numpsy** [comment] 2024-01-24 21:32
I don't see anything that's replacing the bootstrap logger with the settings from the configuration, e.g. https://github.com/serilog/serilog-extensions-hosting/blob/2b8e22185718393e4cdcfb00a8d9fef85930762f/samples/SimpleServiceSample/Program.cs#L37 ?

**Comment by nblumhardt** [comment] 2024-01-24 22:01
Dupe of https://stackoverflow.com/questions/77869833/serilog-net-8-windows-service-worker-using-backgroundservice-logs-not-found

**Closed by nblumhardt** 2024-01-24 22:01 UTC
Labels: duplicate
